openapi: 3.0.3
info:
  title: {{cookiecutter.project_name}}
  description: TODO
  version: 1.0
tags:
  - name: Example

servers:
  - url: "http://localhost:{{cookiecutter.api_port}}"
    description: Local Development

paths:
  /v1/example:
    description: Example endpoint.
    get:
      description: "read example"
      tags:
        - Example
      operationId: getExample
      responses:
        "201":
          description: No content
